const datas = {
  totalRecords: 12,
  scenarios: [
    {
      _id: "1",
      name: "Scenario 1",
      function: "AT, ME, WE",
      title: "Verify chức năng chấm công",
      description:
        "Log request với ngày quá khứ của user Role: user ( và user có work pattern là Cá nhân 08:30 ~ 17:30)",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "2",
      name: "Scenario 2",
      function: "ME, SH",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "3",
      name: "Scenario 3",
      function: "AT, RE",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "4",
      name: "Scenario 4",
      function: "SH, AT, RE",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "5",
      name: "Scenario 5",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "6",
      name: "Scenario 6",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "7",
      name: "Scenario 7",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "18",
      name: "Scenario 8",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "9",
      name: "Scenario 9",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "10",
      name: "Scenario 10",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "11",
      name: "Scenario 11",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
    {
      _id: "12",
      name: "Scenario 12",
      function: "AT",
      title: "Phê duyệt request xin nghỉ",
      description: "Log request xin nghỉ và phê duyệt bởi admin",
      createTime: "19/05/2022",
      updateTime: "19/05/2022",
    },
  ],
};

export default datas;
